### ISSUE TITLE
Rounded sides have no style

### ISSUE THREAD

**Issue by WildEgo** [jaredh159/tailwind-react-native-classnames#95] opened 2021-11-24 21:08 UTC
Hey, thank you fro the amazing library!

I've been messing around with the library and just noticed that rounded-l and rounded-r both do not work, I've tried rounded-t and rounded-b they both do as well as tl, tr, bl and br.

**Comment by jaredh159** [comment] 2021-11-29 20:38
Hmmm... they should work.  I have a [unit test](https://github.com/jaredh159/tailwind-react-native-classnames/blob/master/src/__tests__/borders.spec.ts#L42) for `rounded-l` and I just did a quick check locally, and `rounded-r` seems to be working fine too.  

Are you sure you're using it on a RN component that supports border-radius?  Or you could try `console.log`-ing out the output of your call to `tw` or `tw.style()` to see what you're getting?

**Comment by jaredh159** [comment] 2021-12-05 23:46
closing for now, re-open if you have some more details or steps to reproduce.

**Closed by jaredh159** 2021-12-05 23:46 UTC

**Comment by finnmerlett** [comment] 2022-05-05 01:28
@jaredh159 Just testing this out in my project and it wasn't working. I checked out your unit test, and also looked up the [(view) style properties available](https://reactnative.dev/docs/view-style-props). Looks like setting the corner radii two-at-a-time by specifying a side isn't supported, you can only set them one corner at a time.

I.e. `borderLeftRadius` doesn't exist, it would need to be `borderTopLeftRadius` and `borderBottomLeftRadius`, and presumably the same for the right-radius.
