### ISSUE TITLE
Media queries don't re-render screen with Expo Router

### ISSUE THREAD

**Issue by WKampel** [jaredh159/tailwind-react-native-classnames#318] opened 2024-08-16 15:27 UTC
I'm using Expo Router. When I resize the screen on web, the media queries aren't causing re-renders like they should, so it's not responsive.

I have ` useDeviceContext(tw)` in the root _layout.

**Comment by jaredh159** [comment] 2024-08-28 14:06
closing, pretty sure this would be a dupe of https://github.com/jaredh159/tailwind-react-native-classnames/issues/112 or solvable with memo-busting.

**Closed by jaredh159** 2024-08-28 14:06 UTC

**Comment by chrismou** [comment] 2025-11-11 15:41
Note for anyone who comes across this from Google like I did, you can indeed force the re-render using `tw.memoBuster` on the ThemeProvider tag in Expo Router to solve the issue of class prefix styles not updating on the fly (changing screen size, switching to dark mode, etc).

Basic example:

```javascript
// app/_layout.tsx

import { DarkTheme, DefaultTheme, ThemeProvider } from '@react-navigation/native'
import { Stack } from 'expo-router'
import { useColorScheme } from '@/hooks/useColorScheme'
import tw from '@/helpers/tw'

export default function RootLayout() {
  const colorScheme = useColorScheme()
  useDeviceContext(tw)

  return (
    <ThemeProvider value={colorScheme === 'dark' ? DarkTheme : DefaultTheme} key={tw.memoBuster}>
      <Stack>
        <Stack.Screen name="(tabs)"  />
      </Stack>
    </ThemeProvider>
  )
}

```
