### ISSUE TITLE
(Responsive) React Navigation memoize screens

### ISSUE THREAD

**Issue by JamesHemery** [jaredh159/tailwind-react-native-classnames#186] opened 2022-08-04 14:21 UTC
Hi @jaredh159,

React Navigation memoizes the screens, so when resizing the browser (RN Web), they are not affected by useDeviceContext. 

Do you have a better idea than a custom HOC/Hook on all screens (with usage of useFocusEffect) ?

One other is to use children fn, but it break the React Navigation optimizations. (see https://reactnavigation.org/docs/hello-react-navigation#passing-additional-props)

I think that if we find an effective solution, it will have a good place in the documentation :)

**Comment by jaredh159** [comment] 2022-08-04 15:23
I think this is effectively a duplicate of https://github.com/jaredh159/tailwind-react-native-classnames/issues/112

**Closed by jaredh159** 2022-08-04 15:23 UTC
